# Generated by Django 4.0.1 on 2022-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('numero_cartao', models.CharField(blank=True, max_length=50)),
                ('data_validade', models.CharField(blank=True, max_length=20)),
                ('nome_cartao', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
