# Generated by Django 4.0.1 on 2022-02-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
        ('forma_pagamento', '0002_forma_pagamento_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma_pagamento',
            name='forma_pag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pagamento.pagamento'),
            preserve_default=False,
        ),
    ]
