# Generated by Django 4.0.1 on 2022-02-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma_pagamento', '0003_forma_pagamento_forma_pag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma_pagamento',
            old_name='forma_pag',
            new_name='pagamento',
        ),
    ]
