# Generated by Django 4.0.1 on 2022-01-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(max_length=11)),
                ('rg', models.IntegerField(max_length=10)),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.IntegerField(max_length=11)),
                ('endereco', models.TextField()),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField(max_length=10)),
                ('especialidade', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
                ('area_atuacao', models.CharField(max_length=255)),
            ],
        ),
    ]
