# Generated by Django 4.0.1 on 2022-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='endereco',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='rg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
