# Generated by Django 4.0.1 on 2022-01-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_medicos_cep_alter_medicos_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
