# Generated by Django 4.0.2 on 2022-02-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_medicos_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='endereco',
            field=models.CharField(max_length=300),
        ),
    ]
