# Generated by Django 4.0.1 on 2022-02-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('pagamento', '0001_initial'),
        ('home', '0003_alter_medicos_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.CharField(max_length=400)),
                ('data', models.DateTimeField()),
                ('realizada', models.BinaryField()),
                ('motivo_cancelamento', models.TextField(blank=True, max_length=500)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamento.pagamento')),
            ],
        ),
    ]
