# Generated by Django 4.0.1 on 2022-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True)),
                ('valor', models.FloatField()),
                ('cancelado', models.BinaryField()),
            ],
        ),
    ]
